version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app-network

volumes:
  ollama:

networks:
  app-network:
